version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: taiko
    versions:
    - 1.1.4
    - 1.2.0
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.9
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
